# Sheldon plugin configuration

# Global settings
shell = "zsh"

# Default apply setting for plugins without explicit apply
apply = ["source"]

# Shell completions
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# Additional completions
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

# Syntax highlighting (load last)
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ["{{ name }}.zsh"]

# History substring search
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
use = ["{{ name }}.zsh"]


# FZF tab completion
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

# Better directory navigation
[plugins.zsh-z]
github = "agkozak/zsh-z"

# Git aliases
[plugins.git]
github = "ohmyzsh/ohmyzsh"
use = ["plugins/git/*.zsh"]

# Docker aliases and completions
[plugins.docker]
github = "ohmyzsh/ohmyzsh"
use = ["plugins/docker/*.zsh", "plugins/docker-compose/*.zsh"]

# Kubectl completions
[plugins.kubectl]
github = "ohmyzsh/ohmyzsh"
use = ["plugins/kubectl/*.zsh"]

# Tmux plugin
[plugins.tmux]
github = "ohmyzsh/ohmyzsh"
use = ["plugins/tmux/*.zsh"]

# Templates
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"