"""人が読むための Markdown ビュー (生成物。手で編集しない)。"""
from __future__ import annotations

from .model import CLASSES, Spec, blocked_reasons

HEADER = "<!-- GENERATED by `trs gen` from trs.yaml — DO NOT EDIT -->"


def _cell(s) -> str:
    return str(s if s is not None else "").replace("|", "\\|").replace("\n", " ")


def _table(header, rows):
    out = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    out += ["| " + " | ".join(_cell(c) for c in r) + " |" for r in rows]
    return out


def render(spec: Spec) -> str:
    r = spec.raw
    L = [HEADER, "", f"# {spec.id} {r['title']}", "", f"spec-sha256: `{spec.sha256[:16]}`", ""]

    L += ["## 根拠資料", ""] + _table(["ID", "種別", "参照", "版"],
                                     [[s["id"], s["kind"], s["ref"], s["rev"]] for s in r["sources"]]) + [""]

    if r.get("rules"):
        L += ["## 規則", ""] + _table(
            ["ID", "EARS", "規則", "検査", "根拠"],
            [[x["id"], x["ears"], x["text"], f"`{x['expr']}`" if "expr" in x else f"TLA+ `{x['tla']}`",
              ", ".join(x["basis"])] for x in r["rules"]]) + [""]

    L += ["## 対象範囲", ""] + _table(
        ["US", "UC", "タイトル", *CLASSES, "入力"],
        [[u.story, u.id, u.raw["title"], *(u.scope[c] for c in CLASSES), ", ".join(u.inputs)] for u in spec.use_cases]) + [""]

    for s in r.get("stories", []):
        L += [f"### {s['id']}", "", f"- As a: {s['as_a']}", f"- I want to: {s['i_want']}", f"- So that: {s['so_that']}", ""]

    L += ["## Acceptance Criteria", ""]
    for uc in spec.use_cases:
        L += [f"### {uc.id} {uc.raw['title']}", ""]
        for a in uc.acs:
            blk = blocked_reasons(spec, a)
            L += [f"#### `{a.full_id}` {a.raw['title']}" + (" 🚧" if blk else ""), ""]
            for kw, key in (("Given", "given"), ("When", "when"), ("Then", "then")):
                for i, line in enumerate(a.raw.get(key, [])):
                    L.append(f"- **{kw if i == 0 else 'And'}** {line}")
            L += ["", f"- 事前条件: `{a.raw['pre']}`",
                  "- 期待結果: " + ", ".join(f"{k} = **{v}**" for k, v in a.post.items()),
                  f"- 根拠: {', '.join(a.raw['basis'])}", f"- 組み合わせ: {a.coverage}"]
            if a.raw.get("tla_witness"):
                L.append(f"- TLA+ witness: `{a.raw['tla_witness']}`")
            if blk:
                L.append(f"- ブロック中: {', '.join(blk)}")
            L.append("")

    L += ["## 因子", ""] + _table(["id", "名前", "水準", "確定", "根拠"],
                                 [[f["id"], f["label"], ", ".join(f["levels"]), f["status"], ", ".join(f["basis"])]
                                  for f in spec.factors.values()]) + [""]
    L += ["## 結果", ""] + _table(["id", "名前", "水準"],
                                 [[o["id"], o["label"], ", ".join(o["levels"])] for o in spec.outcomes.values()]) + [""]
    if r.get("assumptions"):
        L += ["## 前提 (起こりえない入力)", ""] + _table(
            ["ID", "内容", "式", "根拠"],
            [[a["id"], a["text"], f"`{a['expr']}`", ", ".join(a["basis"])] for a in r["assumptions"]]) + [""]
    L += ["## Open Issues", ""] + _table(
        ["ID", "内容", "影響", "領域", "状態", "リンク", "解決"],
        [[i["id"], i["text"], ", ".join(i.get("affects", [])), f"`{i['region']}`" if i.get("region") else "",
          i["status"], i.get("link", ""), i.get("resolution", "")] for i in r.get("open_issues", [])]) + [""]
    return "\n".join(L)
